name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Verify Ninja Installation
      run: ninja --version
        
    - name: Fetch llvm code
      run: make fetch
      
    - name: First stage compilation
      run: make llvm-bootstrap

    - name: Second stage compilation
      run: make llvm

    - name: Benchmark
      run: echo make benchmark THREADS=2 # Not running the benchmark due to memory limit
